# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fkidreg',
            new_name='fkidregg',
        ),
    ]
