# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-27 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190428_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fkidregg',
            new_name='fkidreg',
        ),
    ]
