# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-28 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190428_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
