# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-28 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190428_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='balance',
            new_name='balancetable',
        ),
        migrations.RenameModel(
            old_name='login',
            new_name='logintable',
        ),
        migrations.RenameModel(
            old_name='register',
            new_name='registertable',
        ),
    ]
