# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-02 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190428_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='uploadpic'),
        ),
    ]
